services:
  app: &app
    build: .
    restart: always
    volumes:
      - .:/app
      - $HOME/scratch/touche-rad/logs:/var/log
    ports: ["8500:8500"]
    command: fastapi run --reload --port 8500 app.py
    environment:
      - OPENROUTER_API_KEY
      - LOG_PATH=/var/log

  # proxy service
  gensimir:
    build:
      context: ./submission/base
      args:
        BASE_URL: http://app:8500
        MODEL_NAME: gemini-2.5-flash-preview-05-20
    restart: always
    ports: ["8080:8080", "8000:8000"]
    entrypoint: /genirsim/serve.sh
    depends_on:
      app:
        condition: service_started
