[functions.evaluate_utterance]
type = "chat"
user_schema = "functions/evaluate_utterance/user_schema.json"
assistant_schema = "functions/evaluate_utterance/assistant_schema.json"

[functions.evaluate_utterance.variants.gpt_4o_mini]
type = "chat_completion"
model = "openai::gpt-4o-mini"
user_template = "functions/evaluate_utterance/gpt_4o_mini/user_template.minijinja"
assistant_template = "functions/evaluate_utterance/gpt_4o_mini/assistant_template.minijinja"
