# A function defines the task we're tackling (e.g. generating a haiku)...
[functions.chat_completion]
type = "chat"

# ... and a variant is one of many implementations we can use to tackle it (a choice of prompt, model, etc.).
# Since we only have one variant for this function, the gateway will always use it.
[functions.chat_completion.variants.gpt_4o_mini]
type = "chat_completion"
model = "openai::gpt-4o-mini"

# Define the function
[functions.summarize_counterargument]
type = "chat"
user_schema = "functions/schemas/summarize_data_schema.json"

# Define a variant
[functions.summarize_counterargument.variants.default]
type = "chat_completion"
model = "gpt_4o_mini"
user_template = "functions/templates/summarize_data_template.minijinja"
