[project]
name = "submission"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "elasticsearch<9.0.0",
    "fastapi[standard]>=0.115.9",
    "pydantic>=2.11.3",
    "requests>=2.32.3",
]
